"""Add max length to task title

Revision ID: 461f8e19cea4
Revises: 77c694e02f82
Create Date: 2026-08-10 18:50:40.804387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461f8e19cea4'
down_revision: Union[str, Sequence[str], None] = '77c694e02f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_registrations_audit_company_id_fkey'), 'company_registrations_audit', type_='foreignkey')
    op.create_foreign_key(None, 'company_registrations_audit', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('user_directory_company_id_fkey'), 'user_directory', type_='foreignkey')
    op.create_foreign_key(None, 'user_directory', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_directory', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_directory_company_id_fkey'), 'user_directory', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'company_registrations_audit', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('company_registrations_audit_company_id_fkey'), 'company_registrations_audit', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
