"""Make UserDirectory email unique partial

Revision ID: 803902d91238
Revises: 461f8e19cea4
Create Date: 2026-08-12 11:59:51.137028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803902d91238'
down_revision: Union[str, Sequence[str], None] = '461f8e19cea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_registrations_audit_company_id_fkey'), 'company_registrations_audit', type_='foreignkey')
    op.create_foreign_key(None, 'company_registrations_audit', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_public_user_directory_email'), table_name='user_directory')
    op.create_index(op.f('ix_public_user_directory_email'), 'user_directory', ['email'], unique=False, schema='public')
    op.create_index('ix_user_directory_email_unique', 'user_directory', ['email'], unique=True, schema='public', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('user_directory_company_id_fkey'), 'user_directory', type_='foreignkey')
    op.create_foreign_key(None, 'user_directory', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_directory', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_directory_company_id_fkey'), 'user_directory', 'companies', ['company_id'], ['id'])
    op.drop_index('ix_user_directory_email_unique', table_name='user_directory', schema='public', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_public_user_directory_email'), table_name='user_directory', schema='public')
    op.create_index(op.f('ix_public_user_directory_email'), 'user_directory', ['email'], unique=True)
    op.drop_constraint(None, 'company_registrations_audit', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('company_registrations_audit_company_id_fkey'), 'company_registrations_audit', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
